fos_rest:
  serializer:
    serialize_null:  true
  routing_loader:
    include_format: false
  view:
    view_response_listener: true
  format_listener:
    rules:
    - { path: '^/' , stop: true }
    - { path: '^/api', priorities: ['json'], fallback_format: 'json' }

  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
    exception_controller: 'fos_rest.exception.controller:showAction'

  allowed_methods_listener: true
  access_denied_listener:
    json: true
  body_listener: true